#!/usr/bin/python3

import amulet
import requests


def get_dokuwiki_deployment():
    d = amulet.Deployment(series='trusty')
    d.add('dokuwiki')
    d.expose('dokuwiki')
    d.setup(timeout=900)
    d.sentry.wait()
    return d


def is_ipv6_address(address):
    # not a great check - do better?
    return ":" in address


def get_base_url_for_address(address):
    if is_ipv6_address(address):
        return "http://[%s]" % address
    else:
        return "http://" + address


def get_dokuwiki_page(path="/"):
    deployment = get_dokuwiki_deployment()
    unit = deployment.sentry["dokuwiki"][0]
    address = unit.info["public-address"]
    url = get_base_url_for_address(address) + path
    page = requests.get(url)
    return page


def test_dokuwiki_is_reachable():
    page = get_dokuwiki_page()
    assert(page.status_code == 200)


def test_dokuwiki_has_no_errors():
    page = get_dokuwiki_page()
    assert(not "DokuWiki Setup Error" in page.text)
    assert("This topic does not exist yet" in page.text)


def test_internal_files_are_forbidden():
    page = get_dokuwiki_page("/data/pages/wiki/dokuwiki.txt")
    assert(page.status_code == 403)


if __name__ == "__main__":
    test_dokuwiki_is_reachable()
    test_dokuwiki_has_no_errors()
    test_internal_files_are_forbidden()
