#!/usr/bin/python3

import amulet
import requests


def get_dokuwiki_deployment():
    d = amulet.Deployment(series='trusty')
    d.add('dokuwiki')
    d.expose('dokuwiki')
    d.setup()
    d.sentry.wait()
    return d


def is_ipv6_address(address):
    # not a great check - do better?
    return ":" in address


def get_base_url_for_address(address):
    if is_ipv6_address(address):
        return "http://[%s]" % address
    else:
        return "http://" + address


def get_dokuwiki_main_page():
    deployment = get_dokuwiki_deployment()
    unit = deployment.sentry["dokuwiki"][0]
    address = unit.info["public-address"]
    url = get_base_url_for_address(address)
    page = requests.get(url)
    assert(page.status_code == 200)
    return page


def test_dokuwiki_is_reachable():
    get_dokuwiki_main_page()


def test_dokuwiki_has_no_errors():
    page = get_dokuwiki_main_page()
    assert(not "DokuWiki Setup Error" in page.text)
    assert("This topic does not exist yet" in page.text)


if __name__ == "__main__":
    test_dokuwiki_is_reachable()
    test_dokuwiki_has_no_errors()
